### ISSUE TITLE
Tag PHP 8.0 compatibility

### ISSUE THREAD

**Issue by mpbarlow** [claudiodekker/inertia-laravel-testing#11]
Hi

Would it be possible to tag a version with PHP 8.0 compatibility please? I notice the master branch has support for `^8.0` but the latest release (1.1.1) does not.

Installing 1.1.1 via `--ignore-platform-reqs` appears to work fine, but if there are any outstanding compatibility issues I'm happy to try to help via PR!

**Comment by claudiodekker** [comment]
Oops, I was under the impression that I had already done that.
I just tagged `1.2.0`, which should fix this. Let me know if it doesn't!

**Comment by mpbarlow** [comment]
Perfect, thank you!
