### ISSUE TITLE
Failed asserting that stdClass Object is of type array

### ISSUE THREAD

**Issue by AlexJump24** [claudiodekker/inertia-laravel-testing#21]
Hi,

First of all thank you for all the hard work of getting V2 of this package released, really excited to use it. I have just tried to do an initial implementation of this where I am returning a Laravel resource via Inertia.

Example

```
return Inertia::render(
            'Characters',
            [
                'characters' => new CharactersResourceCollection($characters),
            ]
        )->withViewData(['meta' => 'List of characters']);
```

Then as part of my test I am attempting to do the following:-

```
$response = $this->get('/characters');
$response->assertStatus(Response::HTTP_OK);
$response->assertInertia(fn (Assert $inertia) => $inertia
            ->component('Characters', false)
            ->where('characters', fn (Assert $inertia) => $inertia
                ->has('data', 7, function (Assert $a) => $inertia
                       ->where('0.name', 'Iron Man')
                       ->where('1.name', 'Thor')
                });
```

However at this point the assertion is failing as a stdClass is being returned rather than an array, causing `PHPUnit::assertIsArray($props, sprintf('Inertia property [%s] is not scopeable.', $path));` to fail in `Assert.php`

I am not sure whether I am missing something in the documentation, or whether this library currently expecting the props to always be of type array.

**Comment by claudiodekker** [comment]
Hi,

Thanks for letting me know! Looking into it 👍

**Comment by claudiodekker** [comment]
@AlexJump24 I just tagged version `2.2.0`, which includes a fix for this problem 👍

**Comment by AlexJump24** [comment]
Brilliant, thank you so much @claudiodekker 👍
