### ISSUE TITLE
Addition of parameter to revert to assertEquals instead of assertSame in where assertions

### ISSUE THREAD

**Issue by malinky** [claudiodekker/inertia-laravel-testing#30]
I'm new to InertiaJS and I'm really enjoying working with it so far and thank you for this testing package.

In the following test example (similar to that in the docs under the Automatic Eloquent heading) the attributes returned in the users prop from the route are the same as those returned from the User factory, but the order of attributes is different as the model factory will return the id as the last element of the array.

I think this difference in order causes the test to fail because of the assertSame assertion, which is looking for an exact match in both attributes and order.

```
$users = User::factory()->count(2)->create();

$response = $this->get('/users');

$response->assertInertia(fn (InertiaAssert $page) =>
  $page->component('Users/Index')
             ->where('users', $users->toArray())
);
```

I noticed in #27 the assertEquals assertion was replaced with assertSame.

Would it be worth adding a third parameter, maybe called exact or strict to the where method in the Matching trait.

This could default to true and use assertSame but if it was set to false then it could fallback to the less strict assertEquals to allow a test like this to pass. As an example implementation.

```
public function where($key, $value, $exact = true): self
    {
        $this->has($key);

        if ($value instanceof Closure) {
            $prop = $this->prop($key);

            PHPUnit::assertTrue(
                $value(is_array($prop) ? Collection::make($prop) : $prop),
                sprintf('Inertia property [%s] was marked as invalid using a closure.', $this->dotPath($key))
            );
        } elseif ($value instanceof Arrayable) {
            if ($exact) {
                PHPUnit::assertSame(
                    $value->toArray(),
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not exactly match the expected Arrayable.', $this->dotPath($key))
                );
            } else {
                PHPUnit::assertEquals(
                    $value->toArray(),
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not match the expected Arrayable.', $this->dotPath($key))
                );
            }
        } elseif ($value instanceof Responsable) {
            if ($exact) {
                PHPUnit::assertSame(
                    json_decode(json_encode($value->toResponse(request())->getData()), true),
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not exactly match the expected Responsable.', $this->dotPath($key))
                );
            } else {
                PHPUnit::assertEquals(
                    json_decode(json_encode($value->toResponse(request())->getData()), true),
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not match the expected Responsable.', $this->dotPath($key))
                );
            }
        } else {
            if ($exact) {
                PHPUnit::assertSame(
                    $value,
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not exactly match the expected value.', $this->dotPath($key))
                );
            } else {
                PHPUnit::assertEquals(
                    $value,
                    $this->prop($key),
                    sprintf('Inertia property [%s] does not match the expected value.', $this->dotPath($key))
                );
            }
        }

        return $this;
    }
```

**Comment by claudiodekker** [comment]
Hi,

The reason for this change had to do with that (amongst others) `->where('id', true)` would otherwise also succeed when the id is `1`. While I agree that your situation _should_ work, I'm actually somewhat surprised that it isn't. 

I'll see if I can get this fixed without the need for any custom flags on your end. Thanks for letting me know! 👍

**Comment by claudiodekker** [comment]
@malinky I just tagged a new version (`2.2.4`) that solves this issue. Thanks again for reporting it! 👍 

Also, here's something you'll probably like; When writing your tests, you can simply pass in the array directly instead of manually casting it to an array:

```php
$users = User::factory()->count(2)->create();

$this->get('/users')->assertInertia(fn (InertiaAssert $page) => $page
    ->component('Users/Index')
    ->where('users', $users)
);
```

**Comment by malinky** [comment]
@claudiodekker thanks very much for looking at this so quickly. I can see the changes you've made and the test you've added to ensure it's working. Sorry but I've maybe stumbled across another issue which I think relates to sorting when there are created_at and updated_at timestamps in the array which would be generated if using the factory method `create` instead of `make`.

As a similar example to the `the_prop_matches_a_value_using_an_arrayable_even_when_they_are_sorted_differently()` test but using create instead of make I can't get this to pass.

```
$user = User::factory()->create();

$response = $this->makeMockRequest(
    Inertia::render('foo', [
        'bar' => User::first(),
    ])
);

$response->assertInertia(fn (InertiaAssert $inertia) =>
    $inertia->where('bar', $user)
);
```

**Comment by claudiodekker** [comment]
Ugh, you're absolutely right. I really thought I fixed this, but apparently `array_multisort` (what I'm using now) really doesn't always work the way I expected it to. Going to re-fix this using a recursive `ksort` 👍

**Comment by claudiodekker** [comment]
@malinky Alright, I've just tagged a new release (`2.2.5`) for this. Let's hope that finally puts this issue to rest 😅

**Comment by malinky** [comment]
@claudiodekker That's it, the tests are now passing! Thanks again for fixing this so quickly.
