### ISSUE TITLE
[Question] Test partial reload?

### ISSUE THREAD

**Issue by robsontenorio** [claudiodekker/inertia-laravel-testing#36]
Some controllers have `Inertia::lazy(...)`

How to properly test partial reload for that variables?

**Comment by claudiodekker** [comment]
Hi,

In short, this is currently only possible by manually making a request that uses the same _headers_ that Inertia would use internally when requesting to load lazy props. Specifically, the headers you'll want to set are the following two:
```
'X-Inertia-Partial-Component' => 'TheRequestPageComponentName',
'X-Inertia-Partial-Data': 'a,comma,separated,list,of,props',
```

Unfortunately this isn't something we can currently support just yet, but we might revisit this in the near future once the libraries are merged.

Hope this helps!
